/**
 * Async error wrapper to avoid try-catch blocks in route handlers
 */

const catchAsync = (fn) => {
  return (req, res, next) => {
    fn(req, res, next).catch(next);
  };
};

module.exports = catchAsync;
